import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <MainContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>hello</h1>
    </MainContainer>
  );
}

const MainContainer = styled.div`
  margin: 0;
  width: 100vw;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  overflow-x: hidden;
`;
